version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.1
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build